/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi_penjualan_buku;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.Timer;

/**
 *
 * @author hamba allah
 */
public class MENU extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MENU() {
        initComponents();
        //setExtendedState(MAXIMIZED_BOTH);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labeljam = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelstok = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labelinput = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        labelkasir = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        labellaporan = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        labelexit = new javax.swing.JLabel();
        LabelDesktop = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 5));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        labeljam.setFont(new java.awt.Font("Exotc350 DmBd BT", 0, 20)); // NOI18N
        labeljam.setForeground(new java.awt.Color(255, 255, 255));
        labeljam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TOKO BUKU RAFII20");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labeljam, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labeljam, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(220, 20, 60));

        labelstok.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        labelstok.setForeground(new java.awt.Color(255, 255, 255));
        labelstok.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelstok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconn/01stok.png"))); // NOI18N
        labelstok.setText("STOK");
        labelstok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelstokMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelstokMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelstokMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelstok, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelstok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(34, 139, 35));

        labelinput.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        labelinput.setForeground(new java.awt.Color(255, 255, 255));
        labelinput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelinput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconn/02input.png"))); // NOI18N
        labelinput.setText("INPUT");
        labelinput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelinputMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelinputMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelinputMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelinput, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelinput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(62, 254, 255));

        labelkasir.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        labelkasir.setForeground(new java.awt.Color(255, 255, 255));
        labelkasir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelkasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconn/03kasir.png"))); // NOI18N
        labelkasir.setText("KASIR");
        labelkasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelkasirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelkasirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelkasirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelkasir, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelkasir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(253, 215, 3));

        labellaporan.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        labellaporan.setForeground(new java.awt.Color(255, 255, 255));
        labellaporan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labellaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconn/04laporan.png"))); // NOI18N
        labellaporan.setText("LAPORAN");
        labellaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labellaporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labellaporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labellaporanMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labellaporan, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labellaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(220, 20, 60));

        labelexit.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        labelexit.setForeground(new java.awt.Color(255, 255, 255));
        labelexit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconn/05close.png"))); // NOI18N
        labelexit.setText("EXIT");
        labelexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelexitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelexitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelexitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelexit, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelexit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        LabelDesktop.setBackground(new java.awt.Color(220, 20, 60));
        LabelDesktop.setFont(new java.awt.Font("Gill Sans MT", 1, 60)); // NOI18N
        LabelDesktop.setForeground(new java.awt.Color(51, 51, 51));
        LabelDesktop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDesktop.setText("SELAMAT DATANG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        //dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void labelexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelexitMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_labelexitMouseClicked

    private void labelstokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelstokMouseClicked
        // TODO add your handling code here:
        LabelDesktop.removeAll();
        LabelDesktop.repaint();
        STOK OPEN = new STOK();
        OPEN.setVisible(true);
        LabelDesktop.add(OPEN);
    }//GEN-LAST:event_labelstokMouseClicked

    private void labelinputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelinputMouseClicked
        // TODO add your handling code here:
        LabelDesktop.removeAll();
        LabelDesktop.repaint();
        INPUT OPEN = new INPUT();
        OPEN.setVisible(true);
        LabelDesktop.add(OPEN);
    }//GEN-LAST:event_labelinputMouseClicked

    private void labelkasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelkasirMouseClicked
        // TODO add your handling code here:
        LabelDesktop.removeAll();
        LabelDesktop.repaint();
        KASIR OPEN = new KASIR();
        OPEN.setVisible(true);
        LabelDesktop.add(OPEN);
    }//GEN-LAST:event_labelkasirMouseClicked

    private void labellaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labellaporanMouseClicked
        // TODO add your handling code here:
        LabelDesktop.removeAll();
        LabelDesktop.repaint();
        LAPORAN OPEN = new LAPORAN();
        OPEN.setVisible(true);
        LabelDesktop.add(OPEN);
    }//GEN-LAST:event_labellaporanMouseClicked

    private void labelstokMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelstokMouseEntered
        // TODO add your handling code here:
        labelstok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconn/01stok_bw.png")));
        labelstok.setForeground(Color.gray);
    }//GEN-LAST:event_labelstokMouseEntered

    private void labelstokMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelstokMouseExited
        // TODO add your handling code here:
        labelstok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconn/01stok.png")));
        labelstok.setForeground(Color.white);
    }//GEN-LAST:event_labelstokMouseExited

    private void labelinputMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelinputMouseEntered
        // TODO add your handling code here:
        labelinput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconn/02input_bw.png")));
        labelinput.setForeground(Color.gray);
    }//GEN-LAST:event_labelinputMouseEntered

    private void labelinputMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelinputMouseExited
        // TODO add your handling code here:
        labelinput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconn/02input.png")));
        labelinput.setForeground(Color.white);
    }//GEN-LAST:event_labelinputMouseExited

    private void labelkasirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelkasirMouseEntered
        // TODO add your handling code here:
        labelkasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconn/03kasir_bw.png")));
        labelkasir.setForeground(Color.gray);
    }//GEN-LAST:event_labelkasirMouseEntered

    private void labelkasirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelkasirMouseExited
        // TODO add your handling code here:
        labelkasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconn/03kasir.png")));
        labelkasir.setForeground(Color.white);
    }//GEN-LAST:event_labelkasirMouseExited

    private void labellaporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labellaporanMouseEntered
        // TODO add your handling code here:
        labellaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconn/04laporan_bw.png")));
        labellaporan.setForeground(Color.gray);
    }//GEN-LAST:event_labellaporanMouseEntered

    private void labellaporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labellaporanMouseExited
        // TODO add your handling code here:
        labellaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconn/04laporan.png")));
        labellaporan.setForeground(Color.white);
    }//GEN-LAST:event_labellaporanMouseExited

    private void labelexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelexitMouseEntered
        // TODO add your handling code here:
        labelexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconn/05close_bw.png")));
        labelexit.setForeground(Color.gray);
    }//GEN-LAST:event_labelexitMouseEntered

    private void labelexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelexitMouseExited
        // TODO add your handling code here:
        labelexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconn/05close.png")));
        labelexit.setForeground(Color.white);
    }//GEN-LAST:event_labelexitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelDesktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel labelexit;
    private javax.swing.JLabel labelinput;
    private javax.swing.JLabel labeljam;
    private javax.swing.JLabel labelkasir;
    private javax.swing.JLabel labellaporan;
    private javax.swing.JLabel labelstok;
    // End of variables declaration//GEN-END:variables
}
